name: GitHub Actions TP API Weather
on: 
  push:
    branches: [main]
jobs:
  Push_to_registry:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
    - uses: docker/login-action@v2
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_TOKEN: ${{secrets.DOCKER_TOKEN}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_TOKEN
    - name: Build the docker image
      run: docker build . -t efrei-devops-tp2:1.0.0
    - name: Docker push
      run: docker push ${{secrets.DOCKER_USER}}/efrei-tp2-devops
  